target-version = "py38"
line-length = 100
src = ["python", "devops", "export/python"]
extend-exclude = [
  "**/thirdparty/**",
  "**/.venv/**",
  "**/.pytest_cache/**",
  "**/.mypy_cache/**",
  "**/.ruff_cache/**",
  "**/.benchmarks/**",
  "**/build/**",
  "**/dist/**",
]

[lint]
select = [
  "F",
  "E",
  "W",
  "I",
  "B",
  "UP",
  "PERF",
  "SIM",
  "C4",
  "PIE",
  "RET",
  "RSE",
  "A",
  "ARG",
  "DTZ",
  "TCH",
  "RUF",
]
allowed-confusables = [
  "，",
  "。",
  "！",
  "？",
  "：",
  "；",
  "、",
  "（",
  "）",
  "《",
  "》",
  "“",
  "”",
  "‘",
  "’",
  "【",
  "】",
  "—",
  "…",
  "·",
]
ignore = [
  "E501",
  "UP006",
  "UP007",
  "UP045",
  "E402"
]

[lint.isort]
combine-as-imports = true
known-first-party = ["mental1104"]

[lint.per-file-ignores]
"python/test/**/*.py" = ["ARG001", "ARG002", "ARG003", "I001"]
"python/test_benchmark/**/*.py" = ["ARG001", "ARG002", "ARG003", "I001"]

