include mk/preamble.mk
include mk/env.mk
include mk/common-vars.mk
include mk/python.mk
include mk/cpp.mk
include mk/go.mk
include mk/rust.mk
include mk/docker-hooks.mk
include mk/vet-guard.mk
include mk/env-example.mk
include mk/docker.mk
include mk/aggregate.mk
include mk/private.mk
