services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER:     "${PGUSER:?PGUSER 未设置}"
      POSTGRES_PASSWORD: "${PGPASSWORD:?PGPASSWORD 未设置}"
      POSTGRES_DB:       "${PGDATABASE:-postgres}"
    networks:
      - shared_network
    volumes:
      - postgresql-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgresql-data:
    driver: local

networks:
  shared_network:
    external: true