# Auto-generated by generate_init.py (deterministic; hybrid: direct + lazy)
# Do not edit manually.

# ---- Direct imports (safe modules; no mental1104 top-level imports) ----
from mental1104.app.anki import AnkiApkgGenerator
from mental1104.connector.postgres import Base, db_connection, db_params_clickhouse, db_params_postgres, ensure_database_exists, ensure_tables_exist, get_db_config, logger, open_session, params, process_record, sql_query, startup
from mental1104.connector.redis import RedisConnection, RedisLock
from mental1104.csv_processor import csv_processor, csv_writer, export_csv_from_database
from mental1104.deciprobe import ELLIPSIS_CHAR, FUNC_FIELD_WIDTH, HEAD_PREFIX, ID_FIELD_WIDTH, SITE_FIELD_WIDTH, TRACE_IF_ENABLED, TYPE_FIELD_WIDTH, deciprobe, trace_if
from mental1104.encryption import decrypt, encrypt, generate_salt
from mental1104.environment import MissingEnvVarError, check_required_env_vars
from mental1104.file import file_iterator
from mental1104.random import random_pick
from mental1104.schema.common_schema import JsonSerializable
from mental1104.string import replace_space_with
from mental1104.timed import async_timed, get_current_time, parse_time, timed
from mental1104.util import async_delay, delay
from mental1104.utils.parse_json import JsonUtil, dump_json, load_json

# ---- Lazy exports (risky modules; may import mental1104 at top-level) ----
_EXPORT_MAP = {
    'AsyncPulsarAdminHelper': 'mental1104.connector.pulsar',
    'Consumer': 'mental1104.connector.pulsar',
    'CoroutinePool': 'mental1104.concurrency',
    'GatherStrategy': 'mental1104.concurrency',
    'Producer': 'mental1104.connector.pulsar',
    'PulsarAdminHelper': 'mental1104.connector.pulsar',
    'PulsarConnector': 'mental1104.connector.pulsar',
    'PulsarEnvironment': 'mental1104.connector.pulsar',
    'TaskExecutionStrategy': 'mental1104.concurrency',
    'TimeBasedTrendPlot': 'mental1104.plot.trend',
    'TrendPlotBase': 'mental1104.plot.trend',
    'fetch_status': 'mental1104.http_package',
    'iterator_json': 'mental1104.iterator.iterator_json',
}

__all__ = [
    'AnkiApkgGenerator',
    'AsyncPulsarAdminHelper',
    'Base',
    'Consumer',
    'CoroutinePool',
    'ELLIPSIS_CHAR',
    'FUNC_FIELD_WIDTH',
    'GatherStrategy',
    'HEAD_PREFIX',
    'ID_FIELD_WIDTH',
    'JsonSerializable',
    'JsonUtil',
    'MissingEnvVarError',
    'Producer',
    'PulsarAdminHelper',
    'PulsarConnector',
    'PulsarEnvironment',
    'RedisConnection',
    'RedisLock',
    'SITE_FIELD_WIDTH',
    'TRACE_IF_ENABLED',
    'TYPE_FIELD_WIDTH',
    'TaskExecutionStrategy',
    'TimeBasedTrendPlot',
    'TrendPlotBase',
    'async_delay',
    'async_timed',
    'check_required_env_vars',
    'csv_processor',
    'csv_writer',
    'db_connection',
    'db_params_clickhouse',
    'db_params_postgres',
    'deciprobe',
    'decrypt',
    'delay',
    'dump_json',
    'encrypt',
    'ensure_database_exists',
    'ensure_tables_exist',
    'export_csv_from_database',
    'fetch_status',
    'file_iterator',
    'generate_salt',
    'get_current_time',
    'get_db_config',
    'iterator_json',
    'load_json',
    'logger',
    'open_session',
    'params',
    'parse_time',
    'process_record',
    'random_pick',
    'replace_space_with',
    'sql_query',
    'startup',
    'timed',
    'trace_if',
]

def __getattr__(name):
    # PEP 562: lazy attribute access for risky modules & fallback
    try:
        modname = _EXPORT_MAP[name]
    except KeyError:
        raise AttributeError(f'module {__name__} has no attribute {name!r}') from None
    import importlib, types
    mod = importlib.import_module(modname)
    obj = getattr(mod, name, None)
    if obj is None or isinstance(obj, types.ModuleType):
        # 兼容包结构：尝试从子模块 modname.name 再取一次
        try:
            sub = importlib.import_module(f'{modname}.{name}')
        except Exception as _e:  # noqa: F841
            raise AttributeError(f'{modname} has no attribute {name!r}') from None
        obj = getattr(sub, name, None)
        if obj is None:
            raise AttributeError(f'{modname}.{name} has no attribute {name!r}') from None
    globals()[name] = obj  # cache
    return obj

def __dir__():
    return sorted(list(globals().keys()) + list(__all__))
