import os
import ast

"""
This script generates an __init__.py file for the mental1104 package,
collecting all public names from the module files and creating an export list.
"""

BASE_PACKAGE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "mental1104"
)
INIT_FILE = os.path.join(BASE_PACKAGE, "__init__.py")

def collect_public_names(file_path):
    names = []
    with open(file_path, "r", encoding="utf-8") as f:
        try:
            tree = ast.parse(f.read(), filename=file_path)
        except SyntaxError:
            return []

    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Assign)):
            name = getattr(node, "name", None) or getattr(node.targets[0], "id", None)
            if name and not name.startswith("_"):
                names.append(name)
    return names

def walk_modules(base_dir):
    exports = []
    for dirpath, _, filenames in os.walk(base_dir):
        for filename in filenames:
            if filename.endswith(".py") and filename != "__init__.py":
                file_path = os.path.join(dirpath, filename)
                rel_path = os.path.relpath(file_path, BASE_PACKAGE)
                module_path = rel_path.replace(os.path.sep, ".").replace(".py", "")
                module_path = f"mental1104.{module_path}"
                names = collect_public_names(file_path)
                if names:
                    exports.append((module_path, names))
    return exports

def generate_init(exports):
    import_lines = []
    all_names = []
    for module, names in exports:
        import_lines.append(f"from {module} import {', '.join(names)}")
        all_names.extend(names)

    lines = [
        "# Auto-generated by generate_init.py",
        *import_lines,
        "",
        "__all__ = [\n" + ",\n".join(f"    '{name}'" for name in all_names) + "\n]",
    ]
    return "\n".join(lines)

def main():
    exports = walk_modules(BASE_PACKAGE)
    content = generate_init(exports)
    with open(INIT_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✅ Generated {INIT_FILE} with {sum(len(x[1]) for x in exports)} exports.")

if __name__ == "__main__":
    main()
