option(M1104_ENABLE_KAFKA "Enable librdkafka-backed message queue adapter when available" ON)
option(M1104_ENABLE_PULSAR "Enable pulsar-client-cpp-backed adapter when available" ON)

if(M1104_ENABLE_KAFKA)
  find_path(M1104_RDKAFKA_INCLUDE_DIR librdkafka/rdkafkacpp.h)
  find_library(M1104_RDKAFKA_CPP_LIBRARY NAMES rdkafka++)
  find_library(M1104_RDKAFKA_C_LIBRARY NAMES rdkafka)
  if(M1104_RDKAFKA_INCLUDE_DIR AND M1104_RDKAFKA_CPP_LIBRARY AND M1104_RDKAFKA_C_LIBRARY)
    target_include_directories(mental1104 PRIVATE ${M1104_RDKAFKA_INCLUDE_DIR})
    target_link_libraries(mental1104 PRIVATE ${M1104_RDKAFKA_CPP_LIBRARY} ${M1104_RDKAFKA_C_LIBRARY})
    target_compile_definitions(mental1104 PUBLIC M1104_HAS_RDKAFKA=1)
    message(STATUS "Kafka MQ adapter enabled")
  else()
    message(STATUS "Kafka MQ adapter disabled: librdkafka C++ headers/libraries not found")
  endif()
endif()

if(M1104_ENABLE_PULSAR)
  if(DEFINED CMAKE_CXX_STANDARD AND CMAKE_CXX_STANDARD LESS 17)
    message(STATUS "Pulsar MQ adapter disabled for C++${CMAKE_CXX_STANDARD}; current pulsar-client-cpp requires C++17+")
  else()
    find_path(M1104_PULSAR_INCLUDE_DIR pulsar/Client.h)
    find_library(M1104_PULSAR_LIBRARY NAMES pulsar)
    if(M1104_PULSAR_INCLUDE_DIR AND M1104_PULSAR_LIBRARY)
      target_include_directories(mental1104 PRIVATE ${M1104_PULSAR_INCLUDE_DIR})
      target_link_libraries(mental1104 PRIVATE ${M1104_PULSAR_LIBRARY})
      target_compile_definitions(mental1104 PUBLIC M1104_HAS_PULSAR=1)
      message(STATUS "Pulsar MQ adapter enabled")
    else()
      message(STATUS "Pulsar MQ adapter disabled: pulsar-client-cpp headers/library not found")
    endif()
  endif()
endif()
